type AriaAttributes = Partial<{
  'aria-activedescendant': string;
  'aria-atomic': boolean | (string & keyof { true; false });
  'aria-autocomplete': string & keyof { none; inline; list; both };
  'aria-busy': boolean | (string & keyof { true; false });
  'aria-checked': boolean | (string & (keyof { mixed } | keyof { true; false }));
  'aria-colcount': number;
  'aria-colindex': number;
  'aria-colspan': number;
  'aria-controls': string;
  'aria-current':
    | boolean
    | (string & (keyof { page; step; location; date; time } | keyof { true; false }));
  'aria-describedby': string;
  'aria-details': string;
  'aria-disabled': boolean | (string & keyof { true; false });
  'aria-dropeffect': string & keyof { none; copy; execute; link; move; popup };
  'aria-errormessage': string;
  'aria-expanded': boolean | (string & keyof { true; false });
  'aria-flowto': string;
  'aria-grabbed': boolean | (string & keyof { true; false });
  'aria-haspopup':
    | boolean
    | (string & (keyof { menu; listbox; tree; grid; dialog } | keyof { true; false }));
  'aria-hidden': boolean | (string & keyof { true; false });
  'aria-invalid': boolean | (string & (keyof { grammar; spelling } | keyof { true; false }));
  'aria-keyshortcuts': string;
  'aria-label': string;
  'aria-labelledby': string;
  'aria-level': number;
  'aria-live': string & keyof { off; assertive; polite };
  'aria-modal': boolean | (string & keyof { true; false });
  'aria-multiline': boolean | (string & keyof { true; false });
  'aria-multiselectable': boolean | (string & keyof { true; false });
  'aria-orientation': string & keyof { horizontal; vertical };
  'aria-owns': string;
  'aria-placeholder': string;
  'aria-posinset': number;
  'aria-pressed': boolean | (string & (keyof { mixed } | keyof { true; false }));
  'aria-readonly': boolean | (string & keyof { true; false });
  'aria-relevant': string & (keyof { all; additions; removals; text; } | 'additions removals' | 'additions text' | 'removals additions' | 'removals text' | 'text additions' | 'text removals');
  'aria-required': boolean | (string & keyof { true; false });
  'aria-roledescription': string;
  'aria-rowcount': number;
  'aria-rowindex': number;
  'aria-rowspan': number;
  'aria-selected': boolean | (string & keyof { true; false });
  'aria-setsize': number;
  'aria-sort': string & keyof { none; ascending; decending; other };
  'aria-valuemax': number;
  'aria-valuemin': number;
  'aria-valuenow': number;
  'aria-valuetext': string;
  role: string &
    keyof {
      alert;
      alertDialog;
      application;
      article;
      banner;
      button;
      cell;
      checkbox;
      columnheader;
      combobox;
      complementary;
      contentinfo;
      definition;
      dialog;
      directory;
      doument;
      feed;
      figure;
      form;
      grid;
      gridcell;
      group;
      heading;
      img;
      link;
      list;
      listbox;
      listitem;
      log;
      main;
      marquee;
      math;
      menu;
      menubar;
      menuitem;
      menuitemcheckbox;
      menuitemradio;
      navigation;
      none;
      note;
      option;
      presentation;
      progressbar;
      radio;
      radiogroup;
      region;
      row;
      rowgroup;
      rowheader;
      scrollbar;
      search;
      searchbox;
      separator;
      slider;
      spinbutton;
      status;
      switch;
      tab;
      table;
      tablist;
      tabpanel;
      term;
      textbox;
      timer;
      toolbar;
      tree;
      treegrid;
      treeitem;
    };
}>;
